### ISSUE TITLE
Keras Model

### ISSUE THREAD

**Issue by deeplearning987** [Athi223/QuickDrawFlask#1]
Hello @Athi223 
Can you share the keras model?

Can you please mention the steps to be followed for model building and saving the model and include the trained model in flask app ?

 self.model = model_try = load_model('keras.h5')

**Comment by Athi223** [comment]
@deeplearning987 Sure!
Here you go (trained model): https://drive.google.com/file/d/1d94HpyMX3tRrLPmCa3r5jZwAzB9YpiCj/view?usp=sharing

> Can you please mention the steps to be followed for model building and saving the model and include the trained model in flask app ?

This is the Colab notebook i used for training the model, I had partially taken the code from some other repo or tutorial and then dited few parameters in it. Unfortunately I'm not able to trace back to the original source. https://colab.research.google.com/drive/1In1LxY_5Esjsie5Vkd_zvSxOqbmxR0Bs?usp=sharing

**Comment by deeplearning987** [comment]
Hello @Athi223 

How to test by including the model  can you please mention the steps.

**Comment by Athi223** [comment]
> How to test by including the model can you please mention the steps.

All you need to do is copy and paste the model into cloned repo's main directory & rename the model to "keras.py"

Create python3 virtual environment 

Install tensorflow, flask, numpy, pillow

And run `python app.py`

Then simply open up a browser @ `localhost:3000` and the game will be ready

You could just pick some easy titles(skip the difficult ones) as the model is not highly accurate so it'll mostly show **inaccurate** for complex drawings


I'll try to update the readme soon.

**Comment by deeplearning987** [comment]
Hi @Athi223 
I tried running the code.But there's an issue.Can you please help.
Unable to draw any thing 

![Screenshot (34)](https://user-images.githubusercontent.com/89828183/134333482-5b6feb71-d9a3-4cce-a93a-df9a4996b479.png)

**Comment by Athi223** [comment]
I think you should hard refresh the page once, its probably using some other `index.js` (from cache) as it is trying to reference `onnx` at line 10. If you check my code, there is no use of `onnx` library (or any variable named so) in the whole code, let alone at _line 10_.

**Comment by deeplearning987** [comment]
Thanks @Athi223 Its working but all the time it is displaying wrong result. Can you please let me know keras and tensorflow version for model training.

**Comment by Athi223** [comment]
Tensorflow version was 2.4.0
You could use any compatible Keras version i suppose

You might also want to check the image recieved from front end and it's processed version by Pillow, just to be sure it looks as expected

**Comment by deeplearning987** [comment]
Thanks @Athi223
